### ISSUE TITLE
Quick start example no longer works

### ISSUE THREAD

**Issue by ppvk** [luizmineo/node-webkit.dart#5]
When I follow your directions I end up with the node-webkit clouds and an error that says:

Uncaught node.js Error 

TypeError: undefined is not a function
    at dart.J.get$length$asx (file:///home/username/Development/test/build/web/index.dart.js:3629:41)
    at dart.main (file:///home/username/Development/test/build/web/index.dart.js:3499:12)
    at file:///home/username/Development/test/build/web/index.dart.js:4281:7
    at init.currentScript (file:///home/username/Development/test/build/web/index.dart.js:4263:5)
    at file:///home/username/Development/test/build/web/index.dart.js:4276:3
    at file:///home/username/Development/test/build/web/index.dart.js:4286:3

**Comment by Driky** [comment]
The problem come from 
    gui.App.argv.length
if you use 
    gui.App.argv[0]
directly in the string, it works. But if you put something like : 
    var a = gui.App.argv.length;
before the querySelector, the error comes up.
